apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-app
  labels:
    name:  my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  my-app
    spec:
      containers:
      # suryanshvermaa/centos:1.0.0
      # suryanshvermaa/chrome:1.0.0
      # suryanshvermaa/vs-code:1.0.1
      # suryanshvermaa/ubuntu:1.0.0 
      - image: suryanshvermaa/centos:1.0.0
        name:  my-name     
        ports:
        - containerPort:  6901
        env:
          - name: "VNC_PW"
            value: "suryansh"
        
      restartPolicy: Always